{% set name = "dagster_datadog" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: b68fccd9c8dca2a85e0edc2042bf4280e1562ce8cb640cf699bc2b37a80a6779

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - datadog

test:
  imports:
    - dagster_datadog

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-datadog
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Package for datadog Dagster framework components.

extra:
  recipe-maintainers:
    - conda-forge/dagster
